
	
-- 没有头绪让来保护文本不被游戏在启动时改回去，干脆加一个keyevent检查得了（打死）

local i = 0

local function patch()
	if GLOBAL.STRINGS.NAMES.KNOWN_ASPARAGUS_SEEDS == GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS then
		return
	end
	GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS = GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.ASPARAGUS .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_ASPARAGUS_SEEDS = GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS
	GLOBAL.STRINGS.NAMES.CARROT_SEEDS = GLOBAL.STRINGS.NAMES.CARROT_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.CARROT .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_CARROT_SEEDS = GLOBAL.STRINGS.NAMES.CARROT_SEEDS
	GLOBAL.STRINGS.NAMES.CORN_SEEDS = GLOBAL.STRINGS.NAMES.CORN_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.CORN .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_CORN_SEEDS = GLOBAL.STRINGS.NAMES.CORN_SEEDS
	GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS = GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.DRAGONFRUIT .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_DRAGONFRUIT_SEEDS = GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS
	GLOBAL.STRINGS.NAMES.DURIAN_SEEDS = GLOBAL.STRINGS.NAMES.DURIAN_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.DURIAN .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_DURIAN_SEEDS = GLOBAL.STRINGS.NAMES.DURIAN_SEEDS
	GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS = GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.EGGPLANT .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_EGGPLANT_SEEDS = GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS
	GLOBAL.STRINGS.NAMES.GARLIC_SEEDS = GLOBAL.STRINGS.NAMES.GARLIC_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.GARLIC .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_GARLIC_SEEDS = GLOBAL.STRINGS.NAMES.GARLIC_SEEDS
	GLOBAL.STRINGS.NAMES.ONION_SEEDS = GLOBAL.STRINGS.NAMES.ONION_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.ONION .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_ONION_SEEDS = GLOBAL.STRINGS.NAMES.ONION_SEEDS
	GLOBAL.STRINGS.NAMES.PEPPER_SEEDS = GLOBAL.STRINGS.NAMES.PEPPER_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.PEPPER .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_PEPPER_SEEDS = GLOBAL.STRINGS.NAMES.PEPPER_SEEDS
	GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS = GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.POMEGRANATE .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_POMEGRANATE_SEEDS = GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS
	GLOBAL.STRINGS.NAMES.POTATO_SEEDS = GLOBAL.STRINGS.NAMES.POTATO_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.POTATO .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_POTATO_SEEDS = GLOBAL.STRINGS.NAMES.POTATO_SEEDS
	GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS = GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.PUMPKIN .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_PUMPKIN_SEEDS = GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS
	GLOBAL.STRINGS.NAMES.TOMATO_SEEDS = GLOBAL.STRINGS.NAMES.TOMATO_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.TOMATO .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_TOMATO_SEEDS = GLOBAL.STRINGS.NAMES.TOMATO_SEEDS
	GLOBAL.STRINGS.NAMES.TURNIP_SEEDS = GLOBAL.STRINGS.NAMES.TURNIP_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.TURNIP .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_TURNIP_SEEDS = GLOBAL.STRINGS.NAMES.TURNIP_SEEDS
	GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS = GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS .. "(" .. GLOBAL.STRINGS.NAMES.WATERMELON .. ")"
	GLOBAL.STRINGS.NAMES.KNOWN_WATERMELON_SEEDS = GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS
	i = i+1
	print(modname.." patched " .. i.. " times.")
end


GLOBAL.TheInput:AddKeyHandler(function(key, down)
    if down then
        patch()
    end
end)
