-- 没有头绪让来保护文本不被游戏在启动时改回去，干脆加一个keyevent检查得了（打死）

local i = 0


local function patch()
	if GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN == GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1 then
		return
	end
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_2_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_2
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_3_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_3
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_4_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_4
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_5_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_5
	i = i+1
	print(modname.." patched " .. i.. " times.")
end


GLOBAL.TheInput:AddKeyHandler(function(key, down)
    if down then
        patch()
    end
end)
