---
--- Generated by Luanalysis
--- Created by sodiumaluminate.
--- DateTime: 2021/12/18 下午6:54
---

name = "游戏消息桥"
description = [[
一个传送消息的工具，但需要进一步的服务端来中转。
如果你只是想在 QQ 传送消息，那么用 DST-QQ: https://steamcommunity.com/sharedfiles/filedetails/?id=2648728413
]]
author = "NaAlOH4(缝合自 xsluck)"
version = "1.0"
forumthread = "https://gugugu.p.naaloh4.com/kcir"
api_version = 10

dont_starve_compatible = false
reign_of_giants_compatible = false
dst_compatible = true
all_clients_require_mod = false
client_only_mod = false

-- icon = "xs.tex"

configuration_options =
{
    {
        name = "prefix",
        label = "消息前缀",
        hover = "根据消息前是否带 \":\"决定是否转发。",
        options =
        {
            { description = "禁用", data = 0, hover = "一律转发"},
            { description = "启用", data = 1, hover = "只转发以\":\"开头的"},
            { description = "翻转", data = -1, hover = "不转发以\":\"开头的"},
        },
        default = 0,
    },
    {
        name = "escape",
        label = "向服务端发送转义用户名和 id 的消息",
        hover = "用户名对 # 转义，id 对 @ 转义，仅在你的服务端支持转义后才能使用。",
        options =
        {
            { description = "禁用", data = false },
            { description = "启用", data = true },
        },
        default = false,
    },
    {
        name = "mode",
        label = "工作模式",
        hover = "仅当消息服务器和服务器本体不在一起时",
        options =
        {
            { description = "localhost", data = 0, hover = "在服务器搭建的消息服务器，合情合理。" },
            { description = "by hosts", data = 1, hover = "想办法让你的设备能访问域名 dstMessageServer，你可以选择修改 hosts 或者自定义 DNS。"},
            { description = "by hosts + tls", data = 2, hover = "自定义 hosts 的同时，目标服务器需要与当前服务器同步一份自签名的证书"},
            { description = "localhost + tls", data = -1, hover = "这是一个神经病选项，字面意思。(顺便一提，域名就是\"localhost\")"},
        },
        default = 0,
    },
    {
        name = "port",
        label = "端口",
        hover = "消息服务器的端口",
        options =
        {
            { description = "5826", data = "5826", hover = "什么鬼数字？"},
            { description = "80", data = "80", hover = "标准 http 端口。" },
            { description = "8080", data = "8080", hover = "apache？"},
            { description = "443", data = "443", hover = "标准 https 端口。" },
            { description = "22", data = "22", hover = "和 ssh 有仇。"},
            { description = "1080", data = "1080", hover = "和代理有仇。"},
            { description = "7777", data = "7777", hover = "泰拉瑞亚：你礼貌吗？"},
            { description = "3389", data = "3389", hover = "不会吧不会吧 2021 了还有人用 Windows？"},
            { description = "3306", data = "3306", hover = "没压岁钱了！"},
        },
        default = "5826",
    },
}