
	
-- 没有头绪让来保护文本不被游戏在启动时改回去，干脆加一个keyevent检查得了（打死）

local oldStr = {}

oldStr.ASPARAGUS_SEEDS = GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS

local function patch_seeds()
	if GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS == oldStr.ASPARAGUS_SEEDS then
		return
	end
	GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS = _p(GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS, GLOBAL.STRINGS.NAMES.ASPARAGUS)
	GLOBAL.STRINGS.NAMES.KNOWN_ASPARAGUS_SEEDS = GLOBAL.STRINGS.NAMES.ASPARAGUS_SEEDS
	GLOBAL.STRINGS.NAMES.CARROT_SEEDS = _p(GLOBAL.STRINGS.NAMES.CARROT_SEEDS, GLOBAL.STRINGS.NAMES.CARROT)
	GLOBAL.STRINGS.NAMES.KNOWN_CARROT_SEEDS = GLOBAL.STRINGS.NAMES.CARROT_SEEDS
	GLOBAL.STRINGS.NAMES.CORN_SEEDS = _p(GLOBAL.STRINGS.NAMES.CORN_SEEDS, GLOBAL.STRINGS.NAMES.CORN)
	GLOBAL.STRINGS.NAMES.KNOWN_CORN_SEEDS = GLOBAL.STRINGS.NAMES.CORN_SEEDS
	GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS = _p(GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS, GLOBAL.STRINGS.NAMES.DRAGONFRUIT)
	GLOBAL.STRINGS.NAMES.KNOWN_DRAGONFRUIT_SEEDS = GLOBAL.STRINGS.NAMES.DRAGONFRUIT_SEEDS
	GLOBAL.STRINGS.NAMES.DURIAN_SEEDS = _p(GLOBAL.STRINGS.NAMES.DURIAN_SEEDS, GLOBAL.STRINGS.NAMES.DURIAN)
	GLOBAL.STRINGS.NAMES.KNOWN_DURIAN_SEEDS = GLOBAL.STRINGS.NAMES.DURIAN_SEEDS
	GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS = _p(GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS, GLOBAL.STRINGS.NAMES.EGGPLANT)
	GLOBAL.STRINGS.NAMES.KNOWN_EGGPLANT_SEEDS = GLOBAL.STRINGS.NAMES.EGGPLANT_SEEDS
	GLOBAL.STRINGS.NAMES.GARLIC_SEEDS = _p(GLOBAL.STRINGS.NAMES.GARLIC_SEEDS, GLOBAL.STRINGS.NAMES.GARLIC)
	GLOBAL.STRINGS.NAMES.KNOWN_GARLIC_SEEDS = GLOBAL.STRINGS.NAMES.GARLIC_SEEDS
	GLOBAL.STRINGS.NAMES.ONION_SEEDS = _p(GLOBAL.STRINGS.NAMES.ONION_SEEDS, GLOBAL.STRINGS.NAMES.ONION)
	GLOBAL.STRINGS.NAMES.KNOWN_ONION_SEEDS = GLOBAL.STRINGS.NAMES.ONION_SEEDS
	GLOBAL.STRINGS.NAMES.PEPPER_SEEDS = _p(GLOBAL.STRINGS.NAMES.PEPPER_SEEDS, GLOBAL.STRINGS.NAMES.PEPPER)
	GLOBAL.STRINGS.NAMES.KNOWN_PEPPER_SEEDS = GLOBAL.STRINGS.NAMES.PEPPER_SEEDS
	GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS = _p(GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS, GLOBAL.STRINGS.NAMES.POMEGRANATE)
	GLOBAL.STRINGS.NAMES.KNOWN_POMEGRANATE_SEEDS = GLOBAL.STRINGS.NAMES.POMEGRANATE_SEEDS
	GLOBAL.STRINGS.NAMES.POTATO_SEEDS = _p(GLOBAL.STRINGS.NAMES.POTATO_SEEDS, GLOBAL.STRINGS.NAMES.POTATO)
	GLOBAL.STRINGS.NAMES.KNOWN_POTATO_SEEDS = GLOBAL.STRINGS.NAMES.POTATO_SEEDS
	GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS = _p(GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS, GLOBAL.STRINGS.NAMES.PUMPKIN)
	GLOBAL.STRINGS.NAMES.KNOWN_PUMPKIN_SEEDS = GLOBAL.STRINGS.NAMES.PUMPKIN_SEEDS
	GLOBAL.STRINGS.NAMES.TOMATO_SEEDS = _p(GLOBAL.STRINGS.NAMES.TOMATO_SEEDS, GLOBAL.STRINGS.NAMES.TOMATO)
	GLOBAL.STRINGS.NAMES.KNOWN_TOMATO_SEEDS = GLOBAL.STRINGS.NAMES.TOMATO_SEEDS
	GLOBAL.STRINGS.NAMES.TURNIP_SEEDS = _p(GLOBAL.STRINGS.NAMES.TURNIP_SEEDS, GLOBAL.STRINGS.NAMES.TURNIP)
	GLOBAL.STRINGS.NAMES.KNOWN_TURNIP_SEEDS = GLOBAL.STRINGS.NAMES.TURNIP_SEEDS
	GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS = _p(GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS, GLOBAL.STRINGS.NAMES.WATERMELON)
	GLOBAL.STRINGS.NAMES.KNOWN_WATERMELON_SEEDS = GLOBAL.STRINGS.NAMES.WATERMELON_SEEDS
end


oldStr.WAGSTAFF_TOOL_1_LAYMAN = GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN

local function patch_wag()
	if GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN == oldStr.WAGSTAFF_TOOL_1_LAYMAN then
		return
	end
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN = _p(GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1_LAYMAN, GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_1)
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_2_LAYMAN = _p(GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_2_LAYMAN, GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_2)
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_3_LAYMAN = _p(GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_3_LAYMAN, GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_3)
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_4_LAYMAN = _p(GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_4_LAYMAN, GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_4)
	GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_5_LAYMAN = _p(GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_5_LAYMAN, GLOBAL.STRINGS.NAMES.WAGSTAFF_TOOL_5)
end

local function _p(a,b)
	return a.."("..b..")"
end


local function costom_loading()
	if GLOBAL.STRINGS.UI.NOTIFICATION.LOADING == "正在加载" then -- lang is chs and not patched
		GLOBAL.STRINGS.UI.NOTIFICATION.LOADING = "少女祈祷中"
	end
end


GLOBAL.TheInput:AddKeyHandler(function(key, down)
    if down then
        patch_seeds()
        patch_wag()
        costom_loading()
    end
end)
